### PR TITLE
WIP: don't force newline before binops like ++

### PR DESCRIPTION
**Pull request by matklad**
So that's another approach to indenting binary operations: we remove the rule that forces the linebreak before the binary operation. This should help with #137 and #123. The flip side is that we don't force the code to be maximally diff-able.

### CODE REVIEW

**Comment by zimbatm** [comment]
yeah that's better.

Is `;` forced onto a newline or are the examples just not including that?

**Comment by matklad** [comment]
good question: it is currently forced onto the next line, but using the rules which made sense when we special-cased `++`. I've pushed the commit that allows `;` on the next or the current line.

**Comment by zimbatm** [comment]
@matklad :+1: yeah it feels like we're getting into the right path here.

**Pull request merged**
