### PR TITLE
don't indent top-level let

### LINKED ISSUE #92: sample: indented let body
whenever a let..in block is being added, it re-indents the whole body, creating a lot of noise in the diff.

Maybe it's worth special-casing at least for the top-level to not indent the body?

## Input
```nix
{ stdenv, fetchFromGitHub }:
let
pname = "hello";
version = "1.2.3";
in
stdenv.mkDerivation {
  inherit pname version;
  src = fetchFromGitHub {
    owner = "xxx";
    repo = pname;
    rev = version;
    sha256 = "...";
  };
}
```

## Output
```nix
{ stdenv, fetchFromGitHub }:
let
  pname = "hello";
  version = "1.2.3";
in
  stdenv.mkDerivation {
    inherit pname version;
    src = fetchFromGitHub {
      owner = "xxx";
      repo = pname;
      rev = version;
      sha256 = "...";
    };
  }

```

## Desired output

```nix
{ stdenv, fetchFromGitHub }:
let
  pname = "hello";
  version = "1.2.3";
in
stdenv.mkDerivation {
  inherit pname version;
  src = fetchFromGitHub {
    owner = "xxx";
    repo = pname;
    rev = version;
    sha256 = "...";
  };
}
```

### PR DESCRIPTION
**Pull request by matklad**
closes #92

### CODE REVIEW

**Comment by matklad** [comment]
bors retry

looks like a weird CI fluke...

**Comment by zimbatm** [comment]
@matklad it's the pre-commit stuff I added.

Try running `pre-commit run --all-files` to re-format the shell.nix file

**Comment by matklad** [comment]
Fixed! I've also relaxed the minimal pre-commit version, as `1.14` is what is in NixOs stable, and it seems to work fine?

bors +

**Comment by zimbatm** [comment]
Yeah that's fine. It was copied over from the .pre-commit-hook.yaml which requires that newer version (because it fixes an issue with `cargo install`). Since the local pre-commit doesn't try to invoke cargo it's fine.

**Pull request merged**
