### PR TITLE
Minor fix: forcing newline in close parentheses to match node let beh…

### PR DESCRIPTION
**Pull request by Rizary**
According to https://github.com/nix-community/nixpkgs-fmt/issues/178#issuecomment-590905404, odd parentheses behavior still exist after #182.

This PR try to fix both odd behavior placed in `test_data/issue-83-3.bad.nix` and when there is `NODE LET` inside the parentheses so that `test_data/issue-83.2.bad.nix` can pass. 

I still leave the function to detect when parentheses is on top level to make sure all the test case in the future regarding top level parentheses is addressed.

### CODE REVIEW

**Comment by emilazy** [comment]
the `bad` and `good` files seem identical?

**Comment by Rizary** [comment]
@emilazy hi!, yeah actually the purpose is to make sure that `)` doesn't have newline and I forgot to change the indentation on value inside `{}` and  `()`. I have also make some new changes in order to match the parentheses behavior. so actually if we have:
```
{ python3 }:
python3.pkgs.buildPythonApplication {
   propagatedBuildInputs = (with python3.pkgs; [
pkg1
   ]
   );
}
```

it will become:
```
{ python3 }:
python3.pkgs.buildPythonApplication {
  propagatedBuildInputs = (
    with python3.pkgs; [
      pkg1
    ]
  );
}
```

and if  we have it like this:
```
{ python3 }:
python3.pkgs.buildPythonApplication {
   propagatedBuildInputs = (with python3.pkgs; [
pkg1
   ]);
}
```

it will become:
```
{ python3 }:
python3.pkgs.buildPythonApplication {
  propagatedBuildInputs = (with python3.pkgs; [
    pkg1
  ]);
}
```
 the other example if we have:
```
xxx = listToAttrs (
  concatMap (name:
  let a = 4; in 5
));
```
then we have:
```
xxx = listToAttrs (
  concatMap (
    name:
      let a = 4; in 5
  )
);
```

@zimbatm what do you think about the above example? I don't want to fold the `)` up just because someone put it like this:
```
{ python3 }:
python3.pkgs.buildPythonApplication {
   propagatedBuildInputs = (with python3.pkgs; [
pkg1
   ]
   );
}
```

**Comment by Rizary** [comment]
If you also agree with it, then I have to make some changes in some of the existing test case.

**Comment by zimbatm** [comment]
> I don't want to fold the ) up just because someone put it like this

nixpkgs-fmt should never fold lines together, only expand in some specific cases.

**Pull request merged**
