### PR TITLE
Prefer wrapping before binary operators

### LINKED ISSUE #165: sample: `++` folding
nixpkgs-fmt should respect `\n` and never fold lines back into one

## Input
```nix
foo ++
bar
```

## Output
```nix
foo ++ bar

```

## Desired output

```nix
foo
++ bar
```

### PR DESCRIPTION
**Pull request by layus**
Fixes #165. Comments welcome.

This is a bit tricky because it relies on the order of the rules to move
the newline around, and let the previous rules do the right job.

Also, `next_sibling_has_newline` is calling for composition like this,
but I could not make it happen in rust.

```
with_next_sibling(has_newline)
has_newline . next_sibling
next_sibling >>= has_newline
```

### CODE REVIEW

**Comment by layus** [comment]
Rebased, apparently newline() was removed in the meantime.

**Comment by Rizary** [comment]
Thank you for the PR!! 
Yeah about the `newline()`, I think I have slipped my eyes when cleaning up some warning.

wrt to this PR, I have created some test case that I can think of. This is the result:
```
Before:
{
a = "foo" ++
"bar" ++
"lol"
++
"bla"
;

b = str: "foo" ++
( "bar" ++
"${str}" )
++
"bla"
++ (v: "baz" ++
v ++
"qux") str  
;

c =
let x = "foo";
y = "bar"; in x ++
y;
d = let x = "foo"; in (x ++
x);
f = let x = "foo"; in x ++
x;
g = { d = "foo" ++
"bar";};
  
}


After:
{
  a = "foo"
  ++ "bar"
  ++ "lol"
  ++ "bla"
  ;

  b = str: "foo"
  ++ (
    "bar"
    ++ "${str}"
  )
  ++ "bla"
  ++ (
    v: "baz"
    ++ v
    ++ "qux"
  ) str
  ;

  c =
    let
      x = "foo";
      y = "bar";
    in x
    ++ y;
  d = let x = "foo"; in (
    x
    ++ x
  );
  f = let x = "foo"; in x
  ++ x;
  g = {
    d = "foo"
    ++ "bar";
  };

}
```
So far it is good, even though `f` and `d` output is a bit different, I'll merge it soon.

**Comment by layus** [comment]
I guess the discussion should be mainly about cases like this:

```nix
{
  NewBe = [] ++

  # A complex case
  [ "The universe" ] ++

  # Another cae
  [ "me" ]

  # We are done !
  ;
}
```

which becomes

```nix
{
  NewBe = []
  ++ # A complex case
  [ "The universe" ]
  ++ # Another cae
  [ "me" ]

    # We are done !
  ;
}
```

We can see two limitations of this method:

1. We alow only one newline before a bin_op, hence discarding empty lines usedfor separation. I think this is okay, an possiby desirable. And you ?
2. we do not actually move the bin_op after the comment, but it would be better I think. I have however no idea how to do so.

And there is a slight indentation issue with the last comment, irrelevant to this PR I think

**Comment by Rizary** [comment]
@layus Agree on both.

Yeah the last comment is more about indentation.

Thank you!

**Pull request merged**
