### PR TITLE
Fix #126: parentheses and list element rules

### LINKED ISSUE #126: Avoid opening a scope for parentheses and for single-element lists.
Looking at the diff produced by @zimbatm on [discourse](https://discourse.nixos.org/t/nixpkgs-fmt-beta-0-3-1/3812/5?u=layus), the main differences that I see are on using compact forms to avoid extra lines.
For example:

```diff
diff --git a/maintainers/maintainer-list.nix b/maintainers/maintainer-list.nix
index 7ff22fb61fa..87d2ca3aa43 100644
--- a/maintainers/maintainer-list.nix
+++ b/maintainers/maintainer-list.nix
@@ -51,10 +51,12 @@
     name = "Joachim Ernst";
     github = "0x4A6F";
     githubId = 9675338;
-    keys = [{
-      longkeyid = "rsa8192/0x87027528B006D66D";
-      fingerprint = "F466 A548 AD3F C1F1 8C88  4576 8702 7528 B006 D66D";
-    }];
+    keys = [
+      {
+        longkeyid = "rsa8192/0x87027528B006D66D";
+        fingerprint = "F466 A548 AD3F C1F1 8C88  4576 8702 7528 B006 D66D";
+      }
+    ];
   };
   "1000101" = {
     email = "jan.hrnko@satoshilabs.com";
```

and this occurs in many places, like for `fetch*` calls  

```diff
diff --git a/pkgs/development/python-modules/pyscard/default.nix b/pkgs/development/python-modules/pyscard/default.nix
index bab8e502b9c..e601f23ada9 100644
--- a/pkgs/development/python-modules/pyscard/default.nix
+++ b/pkgs/development/python-modules/pyscard/default.nix
@@ -19,10 +19,12 @@ buildPythonPackage rec {
   patches = [
     # Fixes darwin tests
     # See: https://github.com/LudovicRousseau/pyscard/issues/77
-    (fetchpatch {
-      url = "https://github.com/LudovicRousseau/pyscard/commit/62e675028086c75656444cc21d563d9f08ebf8e7.patch";
-      sha256 = "1lr55npcpc8j750vf7vaisqyk18d5f00l7nii2lvawg4sssjaaf7";
-    })
+    (
+      fetchpatch {
+        url = "https://github.com/LudovicRousseau/pyscard/commit/62e675028086c75656444cc21d563d9f08ebf8e7.patch";
+        sha256 = "1lr55npcpc8j750vf7vaisqyk18d5f00l7nii2lvawg4sssjaaf7";
+      }
+    )
   ];
```

There seems to be an implicit rule that collapsing delimiters (parentheses, square brackets and such) is desirable if there is only one expression inside. Furthermore, the collapsing results in a single indent, instead of two (or more).

In short: 

## Input
```nix
{ 
  testA= [(fetchurl {
  url = "bla";
})];

 testB = [( fetchurl{url="bla";} )];
}
```

## Output
```nix
{
  testA = [
    (
      fetchurl {
        url = "bla";
      }
    )
  ];

  testB = [ (fetchurl { url = "bla"; }) ];
}
```

## Desired output

```nix
{
  testA = [ 
    (fetchurl {
      url = "bla";
    })
  ];

  testB = [ (fetchurl { url = "bla"; }) ];
}
```
or

```nix
{
  testA = [ (fetchurl {
    url = "bla";
  }) ];

  testB = [ (fetchurl { url = "bla"; }) ];
}
```

or (mind the space changes)

```nix
{
  testA = [(fetchurl {
    url = "bla";
  })];

  testB = [ (fetchurl { url = "bla"; }) ];
}
```

Of course, when the list constains mutiple elements, we should switch to a safer form.

## Input
```nix
{ 
  testA= [(fetchurl {
  url = "bla";
})(fetchurl {
  url = "foo";
})];

 testB = [( fetchurl{url="bla";} )( fetchurl{url="foo";} )];
}
```

## Output
```nix
{
  testA = [
    (
      fetchurl {
        url = "bla";
      }
    )
    (
      fetchurl {
        url = "foo";
      }
    )
  ];

  testB = [ (fetchurl { url = "bla"; }) (fetchurl { url = "foo"; }) ];
}

```

## Desired output

```nix
{
  testA = [
    (fetchurl {
      url = "bla";
    })
    (fetchurl {
      url = "foo";
    })
  ];

  testB = [ (fetchurl { url = "bla"; }) (fetchurl { url = "foo"; }) ];
}
```

The simplest way to achieve this would be to make parentheses special. When they are expanded (split on several lines) do not force a line break after them. that would still keep the following desired output impossible, but get all the other options above right.

```nix
{
  testA = [(fetchurl {
    url = "bla";
  })];

  testB = [ (fetchurl { url = "bla"; }) ];
}
```

### PR DESCRIPTION
**Pull request by Rizary**
This PR will fix list item and parentheses

### CODE REVIEW

**Comment by layus** [comment]
@Rizary Well done !

Could you explain what this change does ?

For example, here is a diff from nixpkgs. Is it the intended behavior ?

```nix
diff --git a/nixos/modules/programs/venus.nix b/nixos/modules/programs/venus.nix
index 110570ac3f0..05c1247cb5f 100644
--- a/nixos/modules/programs/venus.nix
+++ b/nixos/modules/programs/venus.nix
@@ -16,14 +16,16 @@ let
       cache_directory = ${cfg.cacheDirectory}
       items_per_page = ${toString cfg.itemsPerPage}
       ${(concatStringsSep "\n\n"
-            (map ({ name, feedUrl, homepageUrl }:
-            ''
-              [${feedUrl}]
-              name = ${name}
-              link = ${homepageUrl}
-            '') cfg.feeds))}
+      (map ({ name, feedUrl, homepageUrl }:
+        ''
+          [${feedUrl}]
+          name = ${name}
+          link = ${homepageUrl}
+        ''
+      ) cfg.feeds
+      )
+    )}
     '';
-
 in
 {
 
```

**Comment by Rizary** [comment]
@layus, It isn't. I think I miss several test case, like #178. I'll put it in my next fix.

**Comment by Rizary** [comment]
Anyway, I just search your problem and it seems the problem is because it is inside antiquotations. I am working on it.

**Comment by layus** [comment]
I purposefully avoided described what my problem is with this snippet, to avoid orienting your answer.

My problem is indeed indentation of antiquotations, as reported in #166 and #175. Which are the same actually, it is just that the indent level in #166 is zero, so the code in both follow the same rule that uses the indent of the opening `''` for the antiquotation body.

My other problem is with the two closing parentheses with the same indent level, but on consecutive lines. This is addressed in #178. I, in particular, agree with the comment there that it is the only issues I could find in current master.

```nix
      ) cfg.feeds
      )
```

What remains is more about tastes, so you are nearing the end :-). Congratulations !

**Comment by Rizary** [comment]
Noted, thank you!!

**Comment by Rizary** [comment]
hi @layus, if you have time can you please try the newest commit in #183 ? I think I have fixed the above code.

**Comment by layus** [comment]
Congrats! This looks awesome:

```diff
@@ -424,11 +461,13 @@ in
       default = {};
       type = with types; attrsOf (submodule (
         { name, config, ... }:
-        { options = concreteUnitOptions;
+        {
+          options = concreteUnitOptions;
           config = {
             unit = mkDefault (makeUnit name config);
           };
-        }));
+        }
+      ));
     };
```

Testing again the above code, it gives the following.

```diff
@@ -16,14 +16,13 @@ let
       cache_directory = ${cfg.cacheDirectory}
       items_per_page = ${toString cfg.itemsPerPage}
       ${(concatStringsSep "\n\n"
-            (map ({ name, feedUrl, homepageUrl }:
-            ''
-              [${feedUrl}]
-              name = ${name}
-              link = ${homepageUrl}
-            '') cfg.feeds))}
+      (map ({ name, feedUrl, homepageUrl }:
+        ''
+          [${feedUrl}]
+          name = ${name}
+          link = ${homepageUrl}
+        '') cfg.feeds))}
     '';
```

It seems like there is something weird in the grouping of the last `))}` together. In the other hand, it preserves the original grouping, so it may be acceptable.

Abstracting from the antiquotation indentation, we get 

```nix
${(concatStringsSep "\n\n"
  (map ({ name, feedUrl, homepageUrl }:
    ''
      [${feedUrl}]
      name = ${name}
      link = ${homepageUrl}
    '') cfg.feeds))}
```

Does it look okay to you ? To me it seems a bit crowded.
I would somehow expect the following instead, which separates parentheses groups that were started on different lines. (i.e. it has no gaps in the sequence of lines with decreasing indent.) Not too sure of myself here.

```nix
${(concatStringsSep "\n\n"
  (map ({ name, feedUrl, homepageUrl }:
    ''
      [${feedUrl}]
      name = ${name}
      link = ${homepageUrl}
    ''
  ) cfg.feeds)
)}
```

I guess a nicer way to put this is to name the intermediate mess, but it is outside the scope of a formatter. Let's write a code smell detector now :-).

```nix
${let
  to_section = { name, feedUrl, homepageUrl }: ''
    [${feedUrl}]
    name = ${name}
    link = ${homepageUrl}
  '';
  sections = map to_section cfg.feeds;
in concatStringsSep "\n\n" sections}
```

**Comment by Rizary** [comment]
I am going to check the last example that you mentioned. One thing that caused this is because there is no newline between`(` before `concatStringsep`.

**Pull request merged**
