### PR TITLE
Add fuzzing

### LINKED ISSUE #88: Fuzzing and propery-based testing?
It would be nice to run the code through more extensive tests.

From https://github.com/nix-community/nixpkgs-fmt/issues/70#issuecomment-507333931
> We use libfuzzer-sys in rust-analyzer:
> 
> https://github.com/rust-analyzer/rust-analyzer/tree/master/crates/ra_syntax/fuzz
> 
> https://github.com/rust-fuzz/libfuzzer-sys
>
> Another approach is to use property-based testing + randomized text edits.

### PR DESCRIPTION
**Pull request by matklad**
Results are mixed: fuzzer found a manually injected `if text.starts_with('}') { panic!() }` failure, as well as "nobody needs indent larger than 80" implementation limitation. However, fuzzer wasn't able to replicate #93 :-(

If we want to run this on CI, we should add something like *somewhere*, but I am a little confused about our CI infra. I think I can add this to the end of `ci.sh`, but, ideally, this should run as a parallel CI job

```
rustup run nightly -- cargo fuzz run fmt -- -max_total_time=300
```

closes #88

### CODE REVIEW

**Comment by matklad** [comment]
>However, fuzzer wasn't able to replicate #93 :-(

Well, it did found another similar crash now :D

**Comment by zimbatm** [comment]
Does it depend on rust nightly to work properly?

Maybe with using a build matrix we can achieve some sort of parallelism in Travis CI. Right now everything is run linearly.

**Comment by matklad** [comment]
>Does it depend on rust nightly to work properly?

Yeah, unfortunately it does.

**Comment by grahamc** [comment]
On Wed, Jul 31, 2019, at 7:38 AM, Aleksey Kladov wrote:
> If we want to run this on CI, we should add something like *somewhere*, but I am a little confused about our CI infra. I think I can add this to the end of `ci.sh`, but, ideally, this should run as a parallel CI job


Typically fuzzers run continuously, outside of a typical CI loop. Their cycle to find bugs can be long, and after a bit, a few cycles in CI is typically not sufficient to find problems.

**Comment by Mic92** [comment]
Make it a NixOS module and invite users with too much CPU time to run it :)

**Pull request merged**
