### PR TITLE
Fix #198: Apply parentheses rule when inline with multi-line string

### LINKED ISSUE #198: sample: closing bracket line collapse
Closing brackets in multi line strings don't get collapsed into the previous line.

## Input
```nix
let
  cfg = ''
    ${call
    (value: ''
        ${value}
      ''
    )
  }
  '';
in
cfg

```

## Output
```nix
let
  cfg = ''
    ${call
      (value: ''
        ${value}
      ''
        )
    }
  '';
in
cfg

```

## Desired output

```nix
let
  cfg = ''
    ${call
      (value: ''
        ${value}
      '')
    }
  '';
in
cfg

```

### PR DESCRIPTION
**Pull request by Rizary**

### CODE REVIEW

**Comment by Rizary** [comment]
@zimbatm The latest commit tries to address #203 and changing test_data to meet the implementation in formatting function call.

For high level overview on what is the structure, you can refer to [this file](https://github.com/nix-community/nixpkgs-fmt/blob/9fc897d511bcd6ed80534e117995297bf0a5e9ca/test_data/function_call.good.nix)

**Comment by zimbatm** [comment]
Looks good!

**Comment by Mic92** [comment]
```
unpacking sources
unpacking source archive /nix/store/hr9hll3caf23xy9m8n07p6pfpac2f0cd-nixpkgs-fmt
source root is nixpkgs-fmt
patching sources
configuring
pre-installing dep /nix/store/lqc02b9r36klg1qp20yx9lcj0ypalkcp-nixpkgs-fmt-deps-0.8.0
building
cargo build --release -j 16 -Z unstable-options --out-dir out
   Compiling nixpkgs-fmt v0.8.0 (/build/nixpkgs-fmt)
error[E0008]: cannot bind by-move into a pattern guard
   --> src/rules.rs:307:14
    |
307 |         Some(node) if node.kind() == NODE_ASSERT => {
    |              ^^^^ moves value into pattern guard

error[E0008]: cannot bind by-move into a pattern guard
   --> src/rules.rs:317:14
    |
317 |         Some(node) if node.kind() == NODE_LAMBDA => false,
    |              ^^^^ moves value into pattern guard

error[E0008]: cannot bind by-move into a pattern guard
   --> src/rules.rs:318:14
    |
318 |         Some(node) if node.kind() == NODE_IF_ELSE => false,
    |              ^^^^ moves value into pattern guard

error: aborting due to 3 previous errors

For more information about this error, try `rustc --explain E0008`.
error: Could not compile `nixpkgs-fmt`.

To learn more, run the command again with --verbose.
builder for '/nix/store/ah1wrk7d9ikkzx77mr712q4yn5zhczm8-nixpkgs-fmt-0.8.0.drv' failed with exit code 101
```

**Comment by Rizary** [comment]
On my way to upgrade rust into nightly version.

**Comment by Mic92** [comment]
This cannot by published in nixpkgs for a while than though until it no longer depends on nightly.

**Comment by Rizary** [comment]
Ah, I forgot about that. There is one issue that I need to fix in this PR. I'll see what I can revised in order to be in the upstream nixpkgs.

**Comment by zimbatm** [comment]
Is it possible to write the Rust code in such a way that the stable version of Rust will be able to compile it?

**Comment by Rizary** [comment]
@zimbatm I already fixed the build by refactoring the code.

**Pull request merged**
