### PR TITLE
Wasm GitHub pages

### LINKED ISSUE #23: Add a way for users to submit code samples
As a user I want an easy way to report formatting issues.

A possible implementation would be:

1. Go to a webpage
2. Paste my code. The code is automatically formatted using a WebAssembly build of the project.
3. Change the formatted code to my liking
4. Click "Create issue" and be brought to a pre-filled issue entry on GitHub. ( eg: https://github.com/nix-community/nixpkgs-fmt/issues/new?title=foo&body=bar )

### PR DESCRIPTION
**Pull request by zimbatm**
fixes #23

### CODE REVIEW

**Comment by zimbatm** [comment]
bors: r+

**Comment by grahamc** [comment]
:heart_eyes_cat:

**Comment by grahamc** [comment]
I am _**so excited**_ for this. I tried out the existing version on master at https://nix-community.github.io/nixpkgs-fmt/ and it fails to load a javascript file. Shall I open a new issue?

**Comment by grahamc** [comment]
I will open a new issue :)

**Comment by zimbatm** [comment]
yes with the console error log please :)

**Comment by zimbatm** [comment]
maybe wait until the new version gets deployed: https://travis-ci.com/nix-community/nixpkgs-fmt/builds/114827421

**Pull request merged**
