### PR TITLE
test: condition tests

### PR DESCRIPTION
**Pull request by zimbatm**
multi-line conditions should get indented

It's certainly not covering all of the cases. I haven't really thought about what happens if the condition test is really long for example

### CODE REVIEW

**Comment by Mic92** [comment]
Long conditions should splitted per operator:

This is what black do:

```
a = 1

if a == 1 and a == 2 and a == 3 and a == 4 and a == 5 and a == 6 and a == 7 and a == 8 and a == 9 and a == 10:
    print("foo")
```

```
a = 1

if (
    a == 1
    and a == 2
    and a == 3
    and a == 4
    and a == 5
    and a == 6
    and a == 7
    and a == 8
    and a == 9
    and a == 10
):
    print("foo")
```

**Comment by zimbatm** [comment]
so in nix:
```nix
if
  (cond1 && cond2) ||
  cond3 &&
  cond4
then
  true
else
  false
```

something like that?

**Comment by Mic92** [comment]
I had a quick look int nixpkgs and it seems that taking operators to next line
seems more popular:

```nix
if
  (cond1 && cond2)
  || cond3
  && cond4
then
  true
else
  false
```

Intuitively I would have chosen the same convention.

**Comment by zimbatm** [comment]
Yeah I think this is consistent with the comma-first approach to multi-line function arguments:
```
{ foo
, bar
, baz
}:
null
```

**Pull request closed without merging**
