### PR TITLE
Add missing framework on Darwin

### LINKED ISSUE #7: Build failure on Darwin
On Darwin "cargo build" fails with the following error message:

```
  = note: ld: framework not found Security
          clang-7: error: linker command failed with exit code 1 (use -v to see invocation)
```

I think that `darwin.apple_sdk.frameworks.Security` should be added to the `buildInputs`.

### PR DESCRIPTION
**Pull request by smaret**
Fixes #7

### CODE REVIEW

**Comment by matklad** [comment]
bors ping

**Comment by matklad** [comment]
bors r+

I suspect that this is due to the dependency on `failure` in rnix, which reads backtraces and seems like something that *could* need this Security thing (this is a wild guess though, I don't know a lot about macs). I think rnix should be fixed to just not depend on this library, after which we should be able to remove this dependency, but, in the meantime, it's better to build on darwin than not!

**Comment by Mic92** [comment]
You can check if the final binary depends on this framework.

**Comment by smaret** [comment]
> You can check if the final binary depends on this framework.

It does:

```
% otool -L nixpkgs-fmt
nixpkgs-fmt:
	/System/Library/Frameworks/Security.framework/Versions/A/Security (compatibility version 1.0.0, current version 58286.255.20)
	/nix/store/mffyf74zc4h2wic5lwx0kyx7gvwif0c5-Libsystem-osx-10.12.6/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
	/nix/store/mffyf74zc4h2wic5lwx0kyx7gvwif0c5-Libsystem-osx-10.12.6/lib/libresolv.9.dylib (compatibility version 1.0.0, current version 1.0.0)
```

**Pull request merged**
