### PR TITLE
macOS Big Sur

### PR DESCRIPTION
**Pull request by lrworth**
Build fails on macOS Big Sur due to problems which are resolved in the latest version of nixpkgs master. I've also taken the liberty of running `niv init` to stop `niv update` complaining.

### CODE REVIEW

**Comment by zimbatm** [comment]
do you mind rebasing on top of master? I pushed some fixes to the CI

**Comment by lrworth** [comment]
@zimbatm Done. I'm not sure how to fix the failing checks...

**Comment by zimbatm** [comment]
can you try master again? I did an update at #227

**Comment by lrworth** [comment]
@zimbatm Thanks, master now builds on the new macOS 🎉 

_However_ the new default.nix requires specifying the `.defaultNix` attribute to actually get nixpkgs-fmt. It's fine, just a bit weird and perhaps the default.nix should say something like

```
{ system ? builtins.currentSystem }:
(import ./something.nix { inherit system; }).defaultNix
```
(and put the flake-compat bit in something.nix).

**Pull request closed without merging**
